apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/instance: nodejs-app-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-container
          image: 885300287765.dkr.ecr.us-west-1.amazonaws.com/nodejs-test:build-c4c4dbf4-9c4b-4a73-9015-906abf508291
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/instance: nodejs-app-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
spec:
  type: NodePort
  selector:
    app: nodejs-app
    type: front-end
  ports:
    - port: 9005
      targetPort: 9005
      protocol: TCP
     


