apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/instance: nodejs-app-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
spec:
  type: NodePort
  selector:
    app: nodejs-app
    type: front-end
  ports:
    - port: 9005
      targetPort: 9005
      protocol: TCP
     